// import { z } from "zod";

// import {
//   DocumentType,
//   DocumentOwnerType,
//   DocumentVerificationStatus,
// } from "../../models/Document.model";

// /**
//  * ============================================================
//  * COMMON SCHEMAS
//  * ============================================================
//  */

// /**
//  * MongoDB ObjectId validation
//  */
// const objectIdSchema = z
//   .string()
//   .regex(/^[0-9a-fA-F]{24}$/, "Invalid ID format");

// /**
//  * Date validation
//  *
//  * Accepts:
//  *
//  * - YYYY-MM-DD
//  * - ISO datetime
//  * - JavaScript Date
//  */
// const optionalDateSchema = z
//   .union([
//     z.string().date(),

//     z.string().datetime({
//       offset: true,
//     }),

//     z.date(),
//   ])
//   .optional();

// const requiredDateSchema = z.union([
//   z.string().date(),

//   z.string().datetime({
//     offset: true,
//   }),

//   z.date(),
// ]);

// /**
//  * ============================================================
//  * CREATE DOCUMENT BASE SCHEMA
//  * ============================================================
//  *
//  * IMPORTANT:
//  *
//  * This schema validates ONLY metadata coming from the
//  * frontend.
//  *
//  * It does NOT validate:
//  *
//  * - fileUrl
//  * - originalFileName
//  * - mimeType
//  * - fileSize
//  * - cloudinaryPublicId
//  * - cloudinaryResourceType
//  * - cloudinaryFormat
//  *
//  * Those values are generated by Multer + Cloudinary.
//  */
// const createDocumentBaseSchema = z.object({
//   /**
//    * --------------------------------------------------------
//    * COMPANY
//    * --------------------------------------------------------
//    */
//   companyId: objectIdSchema,

//   /**
//    * --------------------------------------------------------
//    * DOCUMENT TYPE
//    * --------------------------------------------------------
//    */
//   documentType: z.nativeEnum(DocumentType),

//   /**
//    * --------------------------------------------------------
//    * OWNER TYPE
//    * --------------------------------------------------------
//    */
//   ownerType: z.nativeEnum(DocumentOwnerType),

//   /**
//    * --------------------------------------------------------
//    * VEHICLE
//    * --------------------------------------------------------
//    *
//    * Required when ownerType = vehicle.
//    */
//   vehicleId: objectIdSchema.optional(),

//   /**
//    * --------------------------------------------------------
//    * DRIVER
//    * --------------------------------------------------------
//    *
//    * Required when ownerType = driver.
//    */
//   driverId: objectIdSchema.optional(),

//   /**
//    * --------------------------------------------------------
//    * DOCUMENT NUMBER
//    * --------------------------------------------------------
//    */
//   documentNumber: z
//     .string()
//     .trim()
//     .max(100, "Document number cannot exceed 100 characters")
//     .optional()
//     .or(z.literal("")),

//   /**
//    * --------------------------------------------------------
//    * ISSUE DATE
//    * --------------------------------------------------------
//    */
//   issueDate: optionalDateSchema,

//   /**
//    * --------------------------------------------------------
//    * EXPIRY DATE
//    * --------------------------------------------------------
//    *
//    * Required because VCMS is based on expiry monitoring.
//    */
//   expiryDate: requiredDateSchema,

//   /**
//    * --------------------------------------------------------
//    * ISSUING AUTHORITY
//    * --------------------------------------------------------
//    */
//   issuingAuthority: z
//     .string()
//     .trim()
//     .max(150, "Issuing authority cannot exceed 150 characters")
//     .optional()
//     .or(z.literal("")),

//   /**
//    * --------------------------------------------------------
//    * NOTES
//    * --------------------------------------------------------
//    */
//   notes: z
//     .string()
//     .trim()
//     .max(1000, "Notes cannot exceed 1000 characters")
//     .optional()
//     .or(z.literal("")),
// });

// /**
//  * ============================================================
//  * CREATE DOCUMENT VALIDATION
//  * ============================================================
//  *
//  * Cross-field validation:
//  *
//  * Vehicle document:
//  *   vehicleId required
//  *   driverId must not exist
//  *
//  * Driver document:
//  *   driverId required
//  *   vehicleId must not exist
//  *
//  * Also:
//  *
//  * expiryDate >= issueDate
//  */
// export const createDocumentSchema = createDocumentBaseSchema.superRefine(
//   (data, ctx) => {
//     /**
//      * ------------------------------------------------------
//      * VEHICLE DOCUMENT
//      * ------------------------------------------------------
//      */
//     if (data.ownerType === DocumentOwnerType.VEHICLE) {
//       if (!data.vehicleId) {
//         ctx.addIssue({
//           code: z.ZodIssueCode.custom,

//           message: "vehicleId is required for vehicle documents",

//           path: ["vehicleId"],
//         });
//       }

//       if (data.driverId) {
//         ctx.addIssue({
//           code: z.ZodIssueCode.custom,

//           message: "driverId must not be provided for vehicle documents",

//           path: ["driverId"],
//         });
//       }
//     }

//     /**
//      * ------------------------------------------------------
//      * DRIVER DOCUMENT
//      * ------------------------------------------------------
//      */
//     if (data.ownerType === DocumentOwnerType.DRIVER) {
//       if (!data.driverId) {
//         ctx.addIssue({
//           code: z.ZodIssueCode.custom,

//           message: "driverId is required for driver documents",

//           path: ["driverId"],
//         });
//       }

//       if (data.vehicleId) {
//         ctx.addIssue({
//           code: z.ZodIssueCode.custom,

//           message: "vehicleId must not be provided for driver documents",

//           path: ["vehicleId"],
//         });
//       }
//     }

//     /**
//      * ------------------------------------------------------
//      * DATE RELATIONSHIP
//      * ------------------------------------------------------
//      */
//     if (data.issueDate && data.expiryDate) {
//       const issueDate = new Date(data.issueDate);

//       const expiryDate = new Date(data.expiryDate);

//       if (expiryDate < issueDate) {
//         ctx.addIssue({
//           code: z.ZodIssueCode.custom,

//           message: "Expiry date must be after the issue date",

//           path: ["expiryDate"],
//         });
//       }
//     }
//   },
// );

// /**
//  * ============================================================
//  * UPDATE DOCUMENT BASE SCHEMA
//  * ============================================================
//  *
//  * IMPORTANT:
//  *
//  * Do NOT use:
//  *
//  * createDocumentSchema.partial()
//  *
//  * because createDocumentSchema contains superRefine().
//  *
//  * Zod does not allow .partial() directly on an object
//  * schema containing refinements.
//  *
//  * Therefore we use the plain base schema.
//  */
// const updateDocumentBaseSchema = createDocumentBaseSchema.partial();

// /**
//  * ============================================================
//  * UPDATE DOCUMENT VALIDATION
//  * ============================================================
//  *
//  * All fields are optional.
//  *
//  * Cross-field validation is applied only when enough
//  * information is available.
//  */
// export const updateDocumentSchema = updateDocumentBaseSchema.superRefine(
//   (data, ctx) => {
//     /**
//      * ------------------------------------------------------
//      * OWNER TYPE VALIDATION
//      * ------------------------------------------------------
//      *
//      * If ownerType is explicitly supplied during update,
//      * validate the corresponding owner ID.
//      */
//     if (data.ownerType === DocumentOwnerType.VEHICLE) {
//       /**
//        * vehicleId must be supplied when changing
//        * ownerType to vehicle.
//        */
//       if (!data.vehicleId) {
//         ctx.addIssue({
//           code: z.ZodIssueCode.custom,

//           message: "vehicleId is required when ownerType is vehicle",

//           path: ["vehicleId"],
//         });
//       }

//       if (data.driverId) {
//         ctx.addIssue({
//           code: z.ZodIssueCode.custom,

//           message: "driverId must not be provided for vehicle documents",

//           path: ["driverId"],
//         });
//       }
//     }

//     /**
//      * ------------------------------------------------------
//      * DRIVER OWNER
//      * ------------------------------------------------------
//      */
//     if (data.ownerType === DocumentOwnerType.DRIVER) {
//       if (!data.driverId) {
//         ctx.addIssue({
//           code: z.ZodIssueCode.custom,

//           message: "driverId is required when ownerType is driver",

//           path: ["driverId"],
//         });
//       }

//       if (data.vehicleId) {
//         ctx.addIssue({
//           code: z.ZodIssueCode.custom,

//           message: "vehicleId must not be provided for driver documents",

//           path: ["vehicleId"],
//         });
//       }
//     }

//     /**
//      * ------------------------------------------------------
//      * DATE VALIDATION
//      * ------------------------------------------------------
//      *
//      * Only compare dates when both are present in the
//      * update request.
//      *
//      * If only expiryDate is supplied, the service layer
//      * will compare it with the existing issueDate.
//      */
//     if (data.issueDate && data.expiryDate) {
//       const issueDate = new Date(data.issueDate);

//       const expiryDate = new Date(data.expiryDate);

//       if (expiryDate < issueDate) {
//         ctx.addIssue({
//           code: z.ZodIssueCode.custom,

//           message: "Expiry date must be after the issue date",

//           path: ["expiryDate"],
//         });
//       }
//     }
//   },
// );

// /**
//  * ============================================================
//  * DOCUMENT ID VALIDATION
//  * ============================================================
//  */
// export const documentIdSchema = z.object({
//   id: objectIdSchema,
// });

// /**
//  * ============================================================
//  * DOCUMENT QUERY VALIDATION
//  * ============================================================
//  *
//  * Used by:
//  *
//  * GET /api/v1/documents
//  */
// export const documentQuerySchema = z.object({
//   /**
//    * Pagination
//    */
//   page: z.coerce.number().int().min(1).default(1),

//   limit: z.coerce.number().int().min(1).max(100).default(10),

//   /**
//    * Search
//    */
//   search: z.string().trim().optional(),

//   /**
//    * Company
//    */
//   companyId: objectIdSchema.optional(),

//   /**
//    * Document type
//    */
//   documentType: z.nativeEnum(DocumentType).optional(),

//   /**
//    * Owner type
//    */
//   ownerType: z.nativeEnum(DocumentOwnerType).optional(),

//   /**
//    * Vehicle
//    */
//   vehicleId: objectIdSchema.optional(),

//   /**
//    * Driver
//    */
//   driverId: objectIdSchema.optional(),

//   /**
//    * Verification status
//    */
//   verificationStatus: z.nativeEnum(DocumentVerificationStatus).optional(),

//   /**
//    * Expiry range
//    */
//   expiryFrom: z.string().date().optional(),

//   expiryTo: z.string().date().optional(),

//   /**
//    * Expired filter
//    *
//    * Example:
//    *
//    * ?expired=true
//    */
//   expired: z.coerce.boolean().optional(),

//   /**
//    * Expiring within N days
//    *
//    * Example:
//    *
//    * ?expiringWithin=30
//    */
//   expiringWithin: z.coerce.number().int().min(0).max(3650).optional(),

//   /**
//    * Sorting
//    */
//   sortBy: z
//     .enum([
//       "documentType",
//       "documentNumber",
//       "issueDate",
//       "expiryDate",
//       "createdAt",
//     ])
//     .default("createdAt"),

//   sortOrder: z.enum(["asc", "desc"]).default("desc"),
// });

// /**
//  * ============================================================
//  * EXPORT BASE SCHEMA
//  * ============================================================
//  *
//  * Exported only if the service/controller needs it.
//  */
// export { createDocumentBaseSchema, updateDocumentBaseSchema };

import { z } from "zod";

import {
  DocumentType,
  DocumentOwnerType,
  DocumentVerificationStatus,
} from "../../models/Document.model";

/**
 * ============================================================
 * COMMON SCHEMAS
 * ============================================================
 */

/**
 * MongoDB ObjectId validation.
 */
const objectIdSchema = z
  .string()
  .regex(/^[0-9a-fA-F]{24}$/, "Invalid ID format");

/**
 * ============================================================
 * DATE VALIDATION
 * ============================================================
 *
 * Accepted:
 *
 * - YYYY-MM-DD
 * - ISO datetime
 * - JavaScript Date
 *
 * OPTIONAL because OCR may provide the date.
 */
const optionalDateSchema = z
  .union([
    z.string().date(),

    z.string().datetime({
      offset: true,
    }),

    z.date(),
  ])
  .optional();

/**
 * ============================================================
 * CREATE DOCUMENT BASE SCHEMA
 * ============================================================
 */
const createDocumentBaseSchema = z.object({
  /**
   * --------------------------------------------------------
   * COMPANY
   * --------------------------------------------------------
   */
  companyId: objectIdSchema,

  /**
   * --------------------------------------------------------
   * DOCUMENT TYPE
   * --------------------------------------------------------
   */
  documentType: z.nativeEnum(DocumentType),

  /**
   * --------------------------------------------------------
   * OWNER TYPE
   * --------------------------------------------------------
   */
  ownerType: z.nativeEnum(DocumentOwnerType),

  /**
   * --------------------------------------------------------
   * VEHICLE
   * --------------------------------------------------------
   */
  vehicleId: objectIdSchema.optional(),

  /**
   * --------------------------------------------------------
   * DRIVER
   * --------------------------------------------------------
   */
  driverId: objectIdSchema.optional(),

  /**
   * --------------------------------------------------------
   * DOCUMENT NUMBER
   * --------------------------------------------------------
   */
  documentNumber: z
    .string()
    .trim()
    .max(100, "Document number cannot exceed 100 characters")
    .optional()
    .or(z.literal("")),

  /**
   * --------------------------------------------------------
   * ISSUE DATE
   * --------------------------------------------------------
   *
   * Optional because OCR can extract it.
   */
  issueDate: optionalDateSchema,

  /**
   * --------------------------------------------------------
   * EXPIRY DATE
   * --------------------------------------------------------
   *
   * IMPORTANT:
   *
   * OPTIONAL.
   *
   * OCR is responsible for extracting the expiry date.
   *
   * Manual expiry date can still be sent as a fallback.
   */
  expiryDate: optionalDateSchema,

  /**
   * --------------------------------------------------------
   * ISSUING AUTHORITY
   * --------------------------------------------------------
   */
  issuingAuthority: z
    .string()
    .trim()
    .max(150, "Issuing authority cannot exceed 150 characters")
    .optional()
    .or(z.literal("")),

  /**
   * --------------------------------------------------------
   * NOTES
   * --------------------------------------------------------
   */
  notes: z
    .string()
    .trim()
    .max(1000, "Notes cannot exceed 1000 characters")
    .optional()
    .or(z.literal("")),
});

/**
 * ============================================================
 * CREATE DOCUMENT VALIDATION
 * ============================================================
 *
 * Cross-field validation:
 *
 * Vehicle:
 *   vehicleId required
 *   driverId forbidden
 *
 * Driver:
 *   driverId required
 *   vehicleId forbidden
 *
 * Date:
 *   expiryDate >= issueDate
 *
 * IMPORTANT:
 *
 * expiryDate itself is NOT required here.
 *
 * It may come from OCR later.
 */
export const createDocumentSchema = createDocumentBaseSchema.superRefine(
  (data, ctx) => {
    /**
     * ------------------------------------------------------
     * VEHICLE DOCUMENT
     * ------------------------------------------------------
     */
    if (data.ownerType === DocumentOwnerType.VEHICLE) {
      if (!data.vehicleId) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,

          message: "vehicleId is required for vehicle documents",

          path: ["vehicleId"],
        });
      }

      if (data.driverId) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,

          message: "driverId must not be provided for vehicle documents",

          path: ["driverId"],
        });
      }
    }

    /**
     * ------------------------------------------------------
     * DRIVER DOCUMENT
     * ------------------------------------------------------
     */
    if (data.ownerType === DocumentOwnerType.DRIVER) {
      if (!data.driverId) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,

          message: "driverId is required for driver documents",

          path: ["driverId"],
        });
      }

      if (data.vehicleId) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,

          message: "vehicleId must not be provided for driver documents",

          path: ["vehicleId"],
        });
      }
    }

    /**
     * ------------------------------------------------------
     * DATE RELATIONSHIP
     * ------------------------------------------------------
     *
     * Only compare dates when both exist.
     *
     * If expiryDate is missing:
     *
     * OCR service will attempt to extract it.
     */
    if (data.issueDate && data.expiryDate) {
      const issueDate = new Date(data.issueDate);

      const expiryDate = new Date(data.expiryDate);

      if (expiryDate < issueDate) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,

          message: "Expiry date must be after the issue date",

          path: ["expiryDate"],
        });
      }
    }
  },
);

/**
 * ============================================================
 * UPDATE DOCUMENT BASE SCHEMA
 * ============================================================
 *
 * Use plain base schema because createDocumentSchema contains
 * superRefine().
 */
const updateDocumentBaseSchema = createDocumentBaseSchema.partial();

/**
 * ============================================================
 * UPDATE DOCUMENT VALIDATION
 * ============================================================
 */
export const updateDocumentSchema = updateDocumentBaseSchema.superRefine(
  (data, ctx) => {
    /**
     * ------------------------------------------------------
     * VEHICLE OWNER
     * ------------------------------------------------------
     */
    if (data.ownerType === DocumentOwnerType.VEHICLE) {
      if (!data.vehicleId) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,

          message: "vehicleId is required when ownerType is vehicle",

          path: ["vehicleId"],
        });
      }

      if (data.driverId) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,

          message: "driverId must not be provided for vehicle documents",

          path: ["driverId"],
        });
      }
    }

    /**
     * ------------------------------------------------------
     * DRIVER OWNER
     * ------------------------------------------------------
     */
    if (data.ownerType === DocumentOwnerType.DRIVER) {
      if (!data.driverId) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,

          message: "driverId is required when ownerType is driver",

          path: ["driverId"],
        });
      }

      if (data.vehicleId) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,

          message: "vehicleId must not be provided for driver documents",

          path: ["vehicleId"],
        });
      }
    }

    /**
     * ------------------------------------------------------
     * DATE VALIDATION
     * ------------------------------------------------------
     *
     * Only compare when both are supplied.
     */
    if (data.issueDate && data.expiryDate) {
      const issueDate = new Date(data.issueDate);

      const expiryDate = new Date(data.expiryDate);

      if (expiryDate < issueDate) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,

          message: "Expiry date must be after the issue date",

          path: ["expiryDate"],
        });
      }
    }
  },
);

/**
 * ============================================================
 * DOCUMENT ID VALIDATION
 * ============================================================
 */
export const documentIdSchema = z.object({
  id: objectIdSchema,
});

/**
 * ============================================================
 * DOCUMENT QUERY VALIDATION
 * ============================================================
 */
export const documentQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),

  limit: z.coerce.number().int().min(1).max(100).default(10),

  search: z.string().trim().optional(),

  companyId: objectIdSchema.optional(),

  documentType: z.nativeEnum(DocumentType).optional(),

  ownerType: z.nativeEnum(DocumentOwnerType).optional(),

  vehicleId: objectIdSchema.optional(),

  driverId: objectIdSchema.optional(),

  verificationStatus: z.nativeEnum(DocumentVerificationStatus).optional(),

  expiryFrom: z.string().date().optional(),

  expiryTo: z.string().date().optional(),

  expired: z.coerce.boolean().optional(),

  expiringWithin: z.coerce.number().int().min(0).max(3650).optional(),

  sortBy: z
    .enum([
      "documentType",
      "documentNumber",
      "issueDate",
      "expiryDate",
      "createdAt",
    ])
    .default("createdAt"),

  sortOrder: z.enum(["asc", "desc"]).default("desc"),
});

/**
 * ============================================================
 * EXPORT BASE SCHEMA
 * ============================================================
 */
export { createDocumentBaseSchema, updateDocumentBaseSchema };

export default createDocumentSchema;
