import {
  DocumentType,
  DocumentOwnerType,
  DocumentVerificationStatus,
  CloudinaryResourceType,
} from "../models/Document.model";

/**
 * ============================================================
 * CREATE DOCUMENT DTO
 * ============================================================
 *
 * Used for document metadata received from the frontend.
 *
 * IMPORTANT:
 *
 * The frontend does NOT send:
 *
 * - fileUrl
 * - cloudinaryPublicId
 * - cloudinaryResourceType
 * - cloudinaryFormat
 * - fileSize
 *
 * These values are generated by:
 *
 * Multer
 *    ↓
 * Cloudinary
 *    ↓
 * Backend
 */
export interface CreateDocumentDto {
  /**
   * Company that owns the document.
   */
  companyId: string;

  /**
   * Document type.
   */
  documentType: DocumentType;

  /**
   * Document owner.
   *
   * vehicle
   * driver
   */
  ownerType: DocumentOwnerType;

  /**
   * Required when ownerType = vehicle.
   */
  vehicleId?: string;

  /**
   * Required when ownerType = driver.
   */
  driverId?: string;

  /**
   * Document number.
   */
  documentNumber?: string;

  /**
   * Issue date.
   */
  issueDate?: string | Date;

  /**
   * Expiry date.
   *
   * Required for compliance monitoring.
   */
  expiryDate: string | Date;

  /**
   * Issuing authority.
   */
  issuingAuthority?: string;

  /**
   * Additional notes.
   */
  notes?: string;
}

/**
 * ============================================================
 * CLOUDINARY FILE DATA
 * ============================================================
 *
 * Internal backend data generated after Cloudinary upload.
 *
 * This should NOT come directly from the frontend.
 */
export interface CloudinaryFileDto {
  /**
   * Cloudinary secure URL.
   */
  fileUrl: string;

  /**
   * Original uploaded filename.
   */
  originalFileName: string;

  /**
   * MIME type received from Multer.
   */
  mimeType: string;

  /**
   * File size in bytes.
   */
  fileSize: number;

  /**
   * Cloudinary public ID.
   */
  cloudinaryPublicId: string;

  /**
   * Cloudinary resource type.
   */
  cloudinaryResourceType: CloudinaryResourceType;

  /**
   * Cloudinary format.
   */
  cloudinaryFormat?: string;
}

/**
 * ============================================================
 * CREATE DOCUMENT WITH FILE DTO
 * ============================================================
 *
 * Internal service DTO.
 *
 * Combines:
 *
 * Frontend document data
 * +
 * Cloudinary upload result
 */
export interface CreateDocumentWithFileDto
  extends CreateDocumentDto, CloudinaryFileDto {
    file: Express.Multer.File;
  /**
   * User who uploaded the document.
   */
  uploadedBy?: string;
}

/**
 * ============================================================
 * UPDATE DOCUMENT DTO
 * ============================================================
 *
 * All fields are optional because document updates
 * are partial.
 *
 * File fields are optional because a document can be
 * updated without uploading a new file.
 */
export interface UpdateDocumentDto {
  documentType?: DocumentType;

  ownerType?: DocumentOwnerType;

  vehicleId?: string;

  driverId?: string;

  documentNumber?: string;

  issueDate?: string | Date;

  expiryDate?: string | Date;

  issuingAuthority?: string;

  /**
   * New file information.
   *
   * These fields are normally generated by the
   * Cloudinary upload process.
   */
  fileUrl?: string;

  originalFileName?: string;

  mimeType?: string;

  fileSize?: number;

  cloudinaryPublicId?: string;

  cloudinaryResourceType?: CloudinaryResourceType;

  cloudinaryFormat?: string;

  verificationStatus?: DocumentVerificationStatus;

  isOcrProcessed?: boolean;

  extractedText?: string;

  notes?: string;

  verifiedBy?: string;

  verifiedAt?: string | Date;
}

/**
 * ============================================================
 * DOCUMENT QUERY DTO
 * ============================================================
 *
 * Used by:
 *
 * GET /api/v1/documents
 */
export interface DocumentQueryDto {
  /**
   * Pagination.
   */
  page?: number;

  limit?: number;

  /**
   * Search.
   *
   * Searches document number,
   * issuing authority and filename.
   */
  search?: string;

  /**
   * Company filter.
   */
  companyId?: string;

  /**
   * Document type filter.
   */
  documentType?: DocumentType;

  /**
   * Vehicle / Driver filter.
   */
  ownerType?: DocumentOwnerType;

  /**
   * Vehicle filter.
   */
  vehicleId?: string;

  /**
   * Driver filter.
   */
  driverId?: string;

  /**
   * Verification filter.
   */
  verificationStatus?: DocumentVerificationStatus;

  /**
   * Expiry date range.
   */
  expiryFrom?: string;

  expiryTo?: string;

  /**
   * Return only expired documents.
   */
  expired?: boolean;

  /**
   * Return documents expiring within N days.
   *
   * Example:
   *
   * expiringWithin=30
   */
  expiringWithin?: number;

  /**
   * Sorting.
   */
  sortBy?:
    | "documentType"
    | "documentNumber"
    | "issueDate"
    | "expiryDate"
    | "createdAt";

  sortOrder?: "asc" | "desc";
}

/**
 * ============================================================
 * DOCUMENT RESPONSE DTO
 * ============================================================
 *
 * Data returned to the frontend.
 *
 * Includes dynamically calculated:
 *
 * - daysRemaining
 * - complianceStatus
 */
export interface DocumentResponseDto {
  /**
   * MongoDB document ID.
   */
  _id: string;

  /**
   * Company ID.
   */
  companyId: string;

  /**
   * Document type.
   */
  documentType: DocumentType;

  /**
   * Owner type.
   */
  ownerType: DocumentOwnerType;

  /**
   * Vehicle ID.
   */
  vehicleId?: string;

  /**
   * Driver ID.
   */
  driverId?: string;

  /**
   * Document number.
   */
  documentNumber?: string;

  /**
   * Issue date.
   */
  issueDate?: string;

  /**
   * Expiry date.
   */
  expiryDate: string | Date;

  /**
   * Issuing authority.
   */
  issuingAuthority?: string;

  /**
   * Cloudinary secure URL.
   */
  fileUrl: string;

  /**
   * Original filename.
   */
  originalFileName: string;

  /**
   * MIME type.
   */
  mimeType: string;

  /**
   * File size.
   */
  fileSize: number;

  /**
   * Cloudinary public ID.
   *
   * Usually useful for backend operations.
   *
   * It can be omitted from frontend responses
   * later if desired.
   */
  cloudinaryPublicId: string;

  /**
   * Cloudinary resource type.
   */
  cloudinaryResourceType: CloudinaryResourceType;

  /**
   * Cloudinary format.
   */
  cloudinaryFormat?: string;

  /**
   * Verification status.
   */
  verificationStatus: DocumentVerificationStatus;

  /**
   * OCR status.
   */
  isOcrProcessed: boolean;

  /**
   * OCR extracted text.
   */
  extractedText?: string;

  /**
   * Notes.
   */
  notes?: string;

  /**
   * Uploaded by user ID.
   */
  uploadedBy?: string;

  /**
   * Verified by user ID.
   */
  verifiedBy?: string;

  /**
   * Verification date.
   */
  verifiedAt?: string;

  /**
   * ========================================================
   * DYNAMIC COMPLIANCE DATA
   * ========================================================
   *
   * These values are NOT stored in MongoDB.
   */
  daysRemaining?: number;

  complianceStatus: "valid" | "expiring_soon" | "expired";

  createdAt: string;

  updatedAt: string;
}

/**
 * ============================================================
 * DOCUMENT PAGINATION DTO
 * ============================================================
 */
export interface DocumentPaginationDto {
  page: number;

  limit: number;

  total: number;

  totalPages: number;

  hasNextPage: boolean;

  hasPreviousPage: boolean;
}

/**
 * ============================================================
 * DOCUMENT LIST RESPONSE DTO
 * ============================================================
 */
export interface DocumentListResponseDto {
  documents: DocumentResponseDto[];

  pagination: DocumentPaginationDto;
}

/**
 * ============================================================
 * DOCUMENT EXPIRY SUMMARY DTO
 * ============================================================
 *
 * Useful later for:
 *
 * Dashboard
 * Compliance dashboard
 * Alerts
 * Reports
 */
export interface DocumentExpirySummaryDto {
  total: number;

  valid: number;

  expiringSoon: number;

  expired: number;
}

/**
 * ============================================================
 * DOCUMENT EXPIRY ITEM DTO
 * ============================================================
 *
 * Used for compliance alerts.
 */
export interface DocumentExpiryItemDto {
  documentId: string;

  documentType: DocumentType;

  documentNumber?: string;

  companyId: string;

  vehicleId?: string;

  driverId?: string;

  expiryDate?: string | Date;

  daysRemaining?: number;

  complianceStatus: "valid" | "expiring_soon" | "expired";
}
